### ISSUE TITLE
Support constraint based edits

### ISSUE THREAD

**Issue by eborden** [freckle/graphula#22]
`suchThat` is a powerful tool in property based testing. Allowing for patterns like `suchThat` would enable more powerful testing with `graphula`.

One simple way to do this is to pass a `a -> Maybe a`  predicate instead of an `a -> a` on edits. This simplifies the number of `node` functions and makes them more flexible.

```hs
node
  :: forall a m
   . (GraphulaContext m '[a], Dependencies a ~ ())
  => (a -> Maybe a)
  -> m (Entity a)

nodeWith
  :: forall a m. GraphulaContext m '[a]
  => Dependencies a 
  -> (a -> Maybe a)
  -> m (Entity a)
```

This then leads to useful combinators:

```hs
edit :: (a -> a) -> a -> Maybe a
edit f = Just . f
```

```hs
suchThat :: (a -> Bool) -> a -> Maybe a
suchThat p x = x <$ guard (p x)
```

```hs
foo = do
  x <- node @X Just
  y <- node @Y . edit $ set nameLens "doe"
  z <- nodeWith @Z (keys (x, y)) . suchThat $ (> 3) . view ageLens
  pure (x, y, z)
```

As well the `(a -> Maybe a)` combinators then become composable with `>=>`

```hs
nodeWith @Z (keys (x, y))
  $ suchThat . (> 3) . view ageLens
  >=> edit . set legsLens 3
```

**Comment by 5outh** [comment]
One immediate question I have is:

If we're looking to outfit `graphula` with some combinators that exist in `quickcheck`, is it possible that we can reach into `quickcheck` instead to piggyback off of its functionality? Would we prefer something like this?

```haskell
node
  :: forall a m
   . (GraphulaContext m '[a], Dependencies a ~ ())
  => (Maybe (Gen a))
  -> m (Entity a)

edit :: Arbitrary a => (a -> a) -> a -> Gen a
edit f = f <$> arbitrary

suchThat :: Artbitrary a => a -> (a -> Bool) -> Gen a
suchThat x predicate = pure x `suchThat` predicate

-- very similar callsites
```

**Comment by eborden** [comment]
The problem with reaching in to `quickcheck` is that it is currently a `Frontend` and not baked deeply into `graphula`. Though that doesn't mean it is impossible, it just might require some indirection (or not?)
