### ISSUE TITLE
Allow seeded random generation

### ISSUE THREAD

**Issue by eborden** [freckle/graphula#42]
Replay was removed here: https://github.com/freckle/graphula/pull/41

The implementation of replay was never ideal. It required a lot of moving parts and the integration of graphula into our codebase actually makes it hard to utilize.

A better path for replay is probably leaning harder on the PRNG that underlies generation. Instead of logging/loading everything, we should be able to thread the seed for this tests PRNG to create replay-ability. This is likely already possible via hspec or other testing frameworks.

There are some complexities around concurrency, utilizing the seed, etc, that are unknown. Likely `GraphulaT` would need to become a `State` monad to accept and track a PRNG instead of utilizing IO.

**Comment by cdparks** [comment]
I'll have to think about how this interacts with ids that we get back from the DB, since those can't be traced back to the random seed.

**Comment by eborden** [comment]
@cdparks I think IDs you get back from the DB can be thought of as transparent references. They shouldn't interact in any meaningful way with deterministic generation, since the generation is unconcerned with their value.

**Comment by eborden** [comment]
Randomly generated IDs however could interact in a fun way. They'll be deterministic-ally generated, so replay will require clearing entities out of the DB.

**Comment by cdparks** [comment]
I meant more when we use the `Arbitrary` mechanism outside the usual `node` calls:

```haskell

    it "should fetch a null set of unmanaged courses" . withGraph runDB $ do
      -- Uses our generate, and thus our QCGen
      schoolAdmin <- simpleSchoolAdmin
      -- Uses QC's generate, and thus QC's QCGen
      sisId <- liftIO $ generate arbitrary
      -- Back to us
      school <- genAdministeredSchoolWith schoolAdmin $ setField SchoolSisId $ Just sisId
```

**Comment by pbrisbin** [comment]
The export of `Graphula.Arbitrary.generate` solves that now right? If you use that function for these, those would also be deterministic by the passed seed.

**Comment by cdparks** [comment]
Yeah, we'll just need to make sure we're hiding the `Arbitrary` one in our tests.
