### ISSUE TITLE
Does graphula require persistent?

### ISSUE THREAD

**Issue by codygman** [freckle/graphula#47]
Some of my data types don't use persistent, but I still need to declare dependencies on them. I'm guessing Graphula uses Persistents internal representation to figure out dependencies?

Hopefully I'm wrong and Graphula works just fine without persistent :smile:

**Comment by eborden** [comment]
The `HasDependencies` class is how you declare dependencies for a type. The defaults and generic instance work in a "sane" manner, so in most cases you just need to define `Dependencies`.

https://github.com/freckle/graphula/blob/d6ccbbba9d9796bffcfe568368468539bc075a1a/graphula-core/src/Graphula.hs#L344-L353

A dependency could be a `persistent` identifier (`Key Foo`) or it could be any other concrete data type.

See the README for more info: https://github.com/freckle/graphula#dependencies

**Comment by codygman** [comment]
I've been going over the dependencies section, but I'm still a little confused. Maybe I can describe my problem. I have:

```haskell
newtype UserId = UserId Int
data User = User { userId :: UserId }
data Company = Company { companyUsers :: Set.Set UserId }
```

In our tests currently we just do:

```haskell
user <- Helper.insertRandomUser 
company <- Helper.insertRandomCompanyWith $ \company -> company
               { Types.CompanyAssignedUsers = Set.singleton $ userId user
               }
```

I'm not sure how to model "the existence of a user in this set realizes the dependency between user and company".

**Comment by eborden** [comment]
So `User` and `Company` are not managed by `persistent`?

If they were managed by persistent it would look like:

```hs
instance HasDependencies User where

instance HasDependencies User where
  type Dependencies User = Only (Set UserId)
```

```hs
user <- node @User () mempty 
company <- node @User (Only (Set.singleton (entityKey user)) $ edit $ \company -> company
               { Types.CompanyAssignedUsers = Set.singleton $ userId user
               }
```

**Comment by eborden** [comment]
Sorry made a bunch of edits to the sample above. It should be representative now.

**Comment by codygman** [comment]
> So `User` and `Company` are not managed by `persistent`?

That is correct. We've only partially adopted persistent, so that's sort of the context of my question.

**Comment by eborden** [comment]
Originally `graphula` was abstracted away from `persistent`, but it was a lot of gnashing of teeth for little reward. `graphula` is now bound to `persistent`.

**Comment by codygman** [comment]
Okay! That makes it clear I'll have to evaluate moving those things to persistent then.
