### ISSUE TITLE
Update description and README for clarity

### ISSUE THREAD

**Issue by pbrisbin** [freckle/graphula#55]
These details are abstract, from a time when Graphula was meant to be abstracted from any particular storage mechanism. We've since decided being tied to persistent is a valuable simplification. We should update our package description to indicate this coupling, and use more compelling, persistent-specific examples in the README.

**Comment by eborden** [comment]
Is a name change in order as well? We've talked about making it a `persistent-`.

**Comment by pbrisbin** [comment]
I'm not against, but I probably wouldn't be able to do the work for while. So it'll just need a new champion.

**Comment by pbrisbin** [comment]
Lots of improvements in 070645e4fe697f15bd088ee59c6e1c4704684f3d, and I will tweak the `package.yml` as part of next release.
