### ISSUE TITLE
Update package on hackage

### ISSUE THREAD

**Issue by 5outh** [freckle/graphula#57]
In order to add `graphula` as a dependency in my project, I need to pull the most recent version from github. On hackage, the dependency ranges are not up-to-date with the most recent commit.

**Comment by pbrisbin** [comment]
Thanks for the nudge. Not sure why it's mismatched, but we have to relax our upper bounds anyway, so I'll get a release out this week.

Also, :wave:  Hi Ben!

**Comment by cdparks** [comment]
Wait, which pond are you across? _The_ pond?

**Comment by pbrisbin** [comment]
v2.0.0.4 released, [via CI](https://github.com/freckle/graphula/runs/2270149376) no less!

**Comment by 5outh** [comment]
Thanks!
