### ISSUE TITLE
Cannot use with entities not `SafeToInsert`

### ISSUE THREAD

**Issue by pbrisbin** [freckle/graphula#70]
As of lts-21, the version of persistent present needs `SafeToInsert` to use `insert`. This serves as witness that the entity in fact uses an auto-increment key and so is "safe to insert [without explicit key]". Entities where this is _not_ true must use `insertKey` and supply the key. `insertKey`, of course, does not enforce `SafeToInsert`. So safe.

In Graphula, we have only the single `insert` member in the [`MonadGraphulaFrontend`](https://hackage.haskell.org/package/graphula-2.0.2.2/docs/Graphula.html#t:MonadGraphulaFrontend) typeclass. And it always requires (our compatibility type for) `SafeToInsert`. This is because it takes a `Maybe Key` argument and uses `Persist.insert` on `Nothing` (or `Persist.insertKey` on `Just`).

Up until lts-21, this constraint was a no-op and we in fact created cases where we use Graphula on entities that _aren't_ safe to insert. Since we always supplied a `Just key` to our `insert` for these cases (based on `KeySource`), it all worked. But once that constraint becomes actually-enforced, they no longer type check.

At this point, in order to depend on newer persistent and keep up with the latest LTS, we think we need to expand the type-class to include `insertKey`, which will be used by `nodeKeyed` (not `node`), and then we can migrate these non-compiling use-cases.

This calls into question the overall design of `insert`, with its `Maybe` argument, `node` and `KeySource`, etc -- as we seem to be diverging with how persistent is tackling a similar design space. If it turns out we can't avoid a major version bump, we might consider taking larger liberties here.

However, if we _can_ do this as a minor version bump that would be preferred. It could be possible if we give `insertKey` some default. But we have to do that in a way that doesn't keep the `SafeToInsert` constraint on `nodeKeyed` when used. (For example, `insertKey = insert . Just` won't work.) :thinking: 

/cc @tomcarste

**Comment by chris-martin** [comment]
Done in #73
